# Generated by Django 5.0.2 on 2024-05-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0002_facedata_remove_student_facial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='face_embeddings',
            field=models.JSONField(),
        ),
    ]
